# Alembic Configuration File
# the output encoding used when revision files are written from script.py.mako
# this output encoding is not used by Alembic when it listens for changes
# made to .py files.

output_encoding = utf-8

sqlalchemy.url = postgresql://user:password@localhost:5432/smart_ai_learning

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
