from fastapi import APIRouter, Depends, HTTPException, status, Header
from sqlalchemy.orm import Session
from datetime import datetime
from app.database import get_db
from app.models import User, UserProgress, Topic, ProgressStatus
from app.schemas.progress import UserProgressResponse, TopicStartRequest, HintRequest
from app.utils.security import decode_token

router = APIRouter(prefix="/progress", tags=["learning"])


def get_current_user(authorization: str = Header(None), db: Session = Depends(get_db)):
    """Get current user from Authorization header"""
    if not authorization:
        raise HTTPException(status_code=401, detail="Missing authorization header")
    
    try:
        token = authorization.split(" ")[1]
    except IndexError:
        raise HTTPException(status_code=401, detail="Invalid authorization header")
    
    token_data = decode_token(token)
    if token_data is None:
        raise HTTPException(status_code=401, detail="Invalid token")
    
    user = db.query(User).filter(User.id == token_data["user_id"]).first()
    if not user:
        raise HTTPException(status_code=401, detail="User not found")
    return user


@router.get("", response_model=list[UserProgressResponse])
def get_user_progress(current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """Get user's learning progress"""
    progress = db.query(UserProgress).filter(UserProgress.user_id == current_user.id).all()
    return progress


@router.post("/start")
def start_topic(request: TopicStartRequest, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """Start learning a topic"""
    topic = db.query(Topic).filter(Topic.id == request.topic_id).first()
    if not topic:
        raise HTTPException(status_code=404, detail="Topic not found")
    
    progress = db.query(UserProgress).filter(
        UserProgress.user_id == current_user.id,
        UserProgress.topic_id == request.topic_id
    ).first()
    
    if not progress:
        progress = UserProgress(
            user_id=current_user.id,
            topic_id=request.topic_id,
            status=ProgressStatus.IN_PROGRESS
        )
        db.add(progress)
    else:
        progress.status = ProgressStatus.IN_PROGRESS
    
    db.commit()
    db.refresh(progress)
    return {"status": "success", "message": "Topic started"}


@router.get("/topics/{topic_id}/content")
def get_topic_content(topic_id: int, db: Session = Depends(get_db)):
    """Get AI-generated topic teaching content"""
    topic = db.query(Topic).filter(Topic.id == topic_id).first()
    if not topic:
        raise HTTPException(status_code=404, detail="Topic not found")
    
    return {
        "topic_id": topic_id,
        "title": topic.title,
        "description": topic.description,
        "content": topic.content or "Content will be generated by AI",
        "type": topic.type
    }


@router.post("/topics/{topic_id}/hint")
def generate_hint(topic_id: int, request: HintRequest, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """Generate AI hint for a topic"""
    topic = db.query(Topic).filter(Topic.id == topic_id).first()
    if not topic:
        raise HTTPException(status_code=404, detail="Topic not found")
    
    hint = f"Hint for {topic.title}: Consider the fundamental concepts..."
    
    return {
        "topic_id": topic_id,
        "hint": hint
    }


@router.patch("/topics/{topic_id}")
def update_progress(topic_id: int, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """Update topic completion status"""
    progress = db.query(UserProgress).filter(
        UserProgress.user_id == current_user.id,
        UserProgress.topic_id == topic_id
    ).first()
    
    if not progress:
        raise HTTPException(status_code=404, detail="Progress not found")
    
    progress.status = ProgressStatus.COMPLETED
    progress.passed_at = datetime.utcnow()
    
    db.commit()
    db.refresh(progress)
    return {"status": "success", "message": "Topic marked as completed"}
